//
// Created by kugelblitz on 6/10/19.
//

#ifndef INVINCIBLE_CLIENTLOGIC_RESOURCEOFREQUEST_H
#define INVINCIBLE_CLIENTLOGIC_RESOURCEOFREQUEST_H

enum ResourceOfRequest {
    CREATE,
    RESTORE,
    INSERT,
    SELECT,
    UPDATE,
    DELETE
};

#endif //INVINCIBLE_CLIENTLOGIC_RESOURCEOFREQUEST_H
